default:
  image: gitlab.catalyst.net.nz:4567/giscore/geonode/tests/base:latest

  services:
    - gitlab.catalyst.net.nz:4567/giscore/geonode/tests/postgis:latest

test:
  script:
    - export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
    - export PATH=$JAVA_HOME'bin/java':$PATH
    - apt update
    - apt install -y python-virtualenv
    - virtualenv env/
    - source env/bin/activate
    - pip install -U pip
    - pip install -r requirements.txt --upgrade
    - pip install -e .
    - pip install pygdal==`gdal-config --version`.*
    - pip install codecov
