default:
  image: gitlab.catalyst.net.nz:4567/giscore/geonode/tests/base:latest

  services:
    - gitlab.catalyst.net.nz:4567/giscore/geonode/tests/postgis:latest

test:
  script:
  - echo "Hello World"
