default:
  image: gitlab.catalyst.net.nz:4567/giscore/geonode/tests/base:1

  services:
    - mdillon/postgis:9.6

variables:
    POSTGRES_DB: geonode-dev
    POSTGRES_USER: runner
    POSTGRES_PASSWORD: ""

test:
  script:
    - echo "Hello World"
    - psql -h mdillon-postgis -U runner -d geonode-dev -c "create extension postgis"
    # - export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
    # - export PATH=$JAVA_HOME'bin/java':$PATH
    # - apt update
    # - apt install -y python-virtualenv
    # - virtualenv env/
    # - source env/bin/activate
    # - pip install -U pip
    # - pip install -r requirements.txt --upgrade
    # - pip install -e .
    # - pip install pygdal==`gdal-config --version`.*
    # - pip install codecov
